### ISSUE TITLE
Issue at CREATE_TRANSACTION(API) in Staking a amount and voting to a delegate

### ISSUE THREAD

**Issue by bbmarley** [AraiEzzra/DDK.REST.API.CLIENT#36]
Voting for a delegate and Staking money API's of asset parameters of  "createdAt" epoch time is not working

https://github.com/AraiEzzra/DDKCORE/issues/805#issue-562384628

**Comment by AraiEzzra** [comment]
You must specify createdAt in epoch time format. You can use getTime method in our slotService for it https://github.com/AraiEzzra/DDK.REGISTRY/blob/7ccf0534fc5ea4fab8e3323b5f399ffa2b273b00/src/service/slot.ts

https://github.com/AraiEzzra/DDK.REST.API.CLIENT/blob/master/docs/common/epochtime.md
