### ISSUE TITLE
"TESTNET" DDK.REST.API.CLIENT are not responding (Socket hang up)

### ISSUE THREAD

**Issue by bbmarley** [AraiEzzra/DDK.REST.API.CLIENT#39]
Testnet DDK.REST.API.CLIENT is hanging a few times and getting an error

**System i used:**

OS - Ubuntu 16.04.6 LTS-xenial,
Ram - 8GB,
Disk Storage - 100gb

**Get_transactions error:**

![testnet not working gettransactions](https://user-images.githubusercontent.com/43064317/74556117-4844cd00-4f83-11ea-99df-03f329c94521.JPG)

**Server logs data after hanging:**

![APIs are hanging](https://user-images.githubusercontent.com/43064317/74556145-63afd800-4f83-11ea-8755-be717e7e1b4f.JPG)

**Comment by touqeeraslam** [comment]
@bbmarley  We are unable to reproduce this issue. Please try again and let us know if you still face the problem.
